on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  analyse_pull_request:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
        poetry-version: [ 1.1.2 ]
        os: [ ubuntu-18.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Run tests
        run: poetry run pytest --cache-clear --cov=flask_op --cov-report xml:cov.xml --cov-report term-missing tests/ > pytest-coverage.txt
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
